module.exports.RoutesURL = {
    getNewsForUserHomePage: '/api/gnfuhp',
    getLatestNews: '/api/getLatestNews',
    getNewsByFilter: '/api/gnbf',
    getNewsById: '/api/gnbi',
    getHeadLines: '/api/getheadlines',
    getTopNews: '/api/gettopnews',
    getAllNewsByUserId: '/api/getallnewsbyuserid',
    createNews: '/api/createnews',
    createNewsBySelfAdmin: '/api/createnewsbyselfadmin',
    raiseHelpRequest: '/api/raisehelprequest',
    getAllHelpRequest: '/api/getallhelprequests',
    getAllSelfAdminRequests: '/api/getallselfadminrequests',
    registerUser: '/api/registeruser',
    getUserInfoAndNewsCount: '/api/guianc',
    getMyProfileInfo: '/api/getmyprofileinfo',
    updateMyProfile: '/api/updatemyprofile',
    checkIsUserAvailable: '/api/checkisuseravailable',
    changePassword: '/api/changepassword',
    login: '/api/login',
    verifyEmail: '/api/verifyemail',
    verifyUserForgetPassword: '/api/verifyuserforgetpassword',
    verifyOTP: '/api/verifyotp',
    forgetPassword: '/api/forgetpassword',
    uploadProfilePic: '/api/addprofilepiccc',
    approveAndPostNews: '/api/approveandpost',
    updateMainNews: '/api/updateetnews',
    createMainNews: '/api/createnews',
    getLatestNewsSubmittedByUser: '/api/getallnews',
    getTNewsByERefId: '/api/getnewsbyref',
    getAllNewsPostedByUser: '/api/getalluserpostednews',
    getRejectedNews: '/api/getrejectednews',
    getMainNewsByFilter: '/api/getnewsbyfilter',
    getMainNewsByFilter2: '/api/getallnewsad',
    getMainNewsByFilter3: '/api/getallmainnewsbyclientfilter',
    getNewsByFilterAll: '/api/getnewsbyfilterall',
    getUserDetailsById: '/api/getuserdetailsbyid',
    getUserDetailsByIdAndNewsCount: '/api/getuserdetailsbyidandnewscount',
    updateProfileForSelfAdmin: '/api/updateprofileforselfadmin',
    getAllUsersByFilter: '/api/getallusersbyfilter',
    getRejectedUsers: '/api/getrejectedusers',
    getNewsCountByCategory: '/api/getnewscountbycategory',
    updateProfile: '/api/updateprofile',
    getAllNewsPostedByMe: '/api/getallnewspostedbyme',
    sendSelfAdminRequest: '/api/sendselfadminrequest',
    getAllNewsPostedByMeAndFilter: '/api/getallnewspostedbymeandfilter',
    getAllInfoForMyDashboard: '/api/getallinfoformydashboard',
    getAllUsersBySearch: '/api/getallusersbysearch',
    getAllUserPostedNewsByFilter: '/api/getalluserpostednewsbyfilter',


    getHelpRequestsCountByStatus: '/api/getHelpRequestsCountByStatus',
    getHelpRequestsCountByCategory: '/api/getHelpRequestsCountByCategory',
    acceptHelpRequestAndCreate: '/api/accepthelprequestandcreate',
    getAllHelpReqestsForAdmin: '/api/getallhelpreqestsforadmin',
    getAllEnHelpReqestsForAdmin: '/api/getallenhelpreqestsforadmin',
    getHelpRequestInTeByERefId: '/api/getHelpRequestInTeByERefId',
    updateHelpRequestInET: '/api/updateHelpRequestInET',

    postComment: '/api/postcomment',
    getCommentsByRef: '/api/getcommentsbyref',
    saveQuestion: '/api/savequestion',
    getQAsByRefId: '/api/getqasbyrefid',

    getPosts: '/api/getposts',
    saveQuery: '/api/saveQuery',
    SavePersonInfo: '/api/savepersoninfo',
    updatePost: '/api/updatePost',
    getPollOptionsByRefId: '/api/getpolloptionsbyrefId',
    SavePollResults: '/api/savepollresults',

    getPollResultsByRefId: '/api/getpollresultsbyrefid',
    checkIsUserIsPolled: '/api/checkisuserispolled',

    checkIsRequestSubmitted: '/api/checkisrequestsubmitted',
    getMyHelpRequests: '/api/getmyhelprequests',
    getUsersCountByAccountStatus: '/api/getUsersCountByAccountStatus',
    getNewsCountByStatus: '/api/getNewsCountByStatus',
    getAllUsersByFilter3: '/api/getAllUsersByFilter3',

    getAllUserNewsForAdmin: '/api/getAllUserNewsForAdmin',

    getAllPostsForAdmin: '/api/getAllPostsForAdmin',
    getPostsCountByStatus: '/api/getPostsCountByStatus',

    deleteUploadedFile: '/api/deleteUploadedFile',
    getAllFiles: '/api/getallfiles',
    getFilesByFilterAll: '/api/getFilesByFilterAll',

    addImages: '/api/addImages',
    getImages: '/api/getImages',
    updateImage: '/api/updateImage',

    addImagesM: '/api/addImagesm',
    getImagesM: '/api/getImagesm',
    updateImageM: '/api/updateImagem',
    raiseDonationRequest: '/api/raiseDonationRequest',
    updateDonationRequest: '/api/updateDonationRequest',
    downloadfile : '/api/downloadfile',
    deleteFile : '/api/deleteFile'
}


